#!/bin/sh
echo -e "
Correct Location of this bash version:\n
curl -O https://raw.github.com/cPanelTechs/TechScripts/master/authdns.sh > authdns.sh; chmod u+x authdns.sh\n\n

Location of the new perl version:\n
http://nscheck.qlogicinc.com/\n\n

Docs:\n
https://staffwiki.cpanel.net/LinuxSupport/GuideToDns#Bash_script_to_show_authoritative_nameservers_and_GLUE_records"
